### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [jdagnogo/Alerte-leboncoin-appart#1]
Bonjour,

Serait il possible que tu regardes pour ajouter cette appli dans le dépôt officiel de F-Droid? Il n'y a que des applis sous licence libre et open-source dans cet appstore, la tienne y a sa place :) Tu trouveras de la doc sur le site pour savoir comment publier ton appli : https://f-droid.org/

Par ailleurs, il faudra que tu tagues tes releases sur github pour que ça marche

**Comment by jdagnogo** [comment]
Ca marche ! faut juste que je trouve le temps de le faire ^^

**Comment by Poussinou** [comment]
Cool :)
